/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import javax.swing.SwingConstants;
import tools.MainModel;
import tools.Controller;
/**
 *
 * @author mfaja
 */
public class ViewAnalysis extends javax.swing.JFrame  {
    Controller cl;
    MainModel mm;
    /**
     * Creates new form Main
     */
    public ViewAnalysis() {
        
        initComponents();
        cl = new Controller();
        mm = new MainModel();
        cl.setMo(mm);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelLineChart = new javax.swing.JPanel();
        Jan = new javax.swing.JProgressBar(SwingConstants.VERTICAL);
        jButton1 = new javax.swing.JButton();
        Feb = new javax.swing.JProgressBar(SwingConstants.VERTICAL);
        Mei = new javax.swing.JProgressBar(SwingConstants.VERTICAL);
        Mar = new javax.swing.JProgressBar(SwingConstants.VERTICAL);
        Apr = new javax.swing.JProgressBar(SwingConstants.VERTICAL);
        Jul = new javax.swing.JProgressBar(SwingConstants.VERTICAL);
        Aug = new javax.swing.JProgressBar(SwingConstants.VERTICAL);
        Sep = new javax.swing.JProgressBar(SwingConstants.VERTICAL);
        Des = new javax.swing.JProgressBar(SwingConstants.VERTICAL);
        Nov = new javax.swing.JProgressBar(SwingConstants.VERTICAL);
        Jun = new javax.swing.JProgressBar(SwingConstants.VERTICAL);
        Okt = new javax.swing.JProgressBar(SwingConstants.VERTICAL);
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        JanLab = new javax.swing.JLabel();
        FebLab = new javax.swing.JLabel();
        MarLab = new javax.swing.JLabel();
        AprLab = new javax.swing.JLabel();
        MayLab = new javax.swing.JLabel();
        JunLab = new javax.swing.JLabel();
        JulLab = new javax.swing.JLabel();
        SepLab = new javax.swing.JLabel();
        OktLab = new javax.swing.JLabel();
        NovLab = new javax.swing.JLabel();
        DesLab = new javax.swing.JLabel();
        AugLab = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelImport = new javax.swing.JPanel();
        importData = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelData = new javax.swing.JPanel();
        importData1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelQuit = new javax.swing.JPanel();
        importData2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 161, 156));

        jButton1.setBackground(new java.awt.Color(124, 209, 184));
        jButton1.setText("Refresh");
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Jan");

        jLabel7.setText("Feb");

        jLabel8.setText("Mar");

        jLabel9.setText("Apr");

        jLabel10.setText("May");

        jLabel11.setText("Jun");

        jLabel12.setText("Jul");

        jLabel13.setText("Aug");

        jLabel14.setText("Sept");

        jLabel15.setText("Okt");

        jLabel16.setText("Nov");

        jLabel17.setText("Des");

        jButton2.setBackground(new java.awt.Color(250, 187, 81));
        jButton2.setText("Analyzing");
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Grafik Profit");

        JanLab.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        JanLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JanLab.setText(" ");

        FebLab.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        FebLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FebLab.setText(" ");

        MarLab.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        MarLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MarLab.setText(" ");

        AprLab.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        AprLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AprLab.setText(" ");

        MayLab.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        MayLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MayLab.setText(" ");

        JunLab.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        JunLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JunLab.setText(" ");

        JulLab.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        JulLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JulLab.setText(" ");

        SepLab.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        SepLab.setText(" ");

        OktLab.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        OktLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OktLab.setText(" ");

        NovLab.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        NovLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NovLab.setText(" ");

        DesLab.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        DesLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DesLab.setText(" ");

        AugLab.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        AugLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AugLab.setText(" ");

        javax.swing.GroupLayout panelLineChartLayout = new javax.swing.GroupLayout(panelLineChart);
        panelLineChart.setLayout(panelLineChartLayout);
        panelLineChartLayout.setHorizontalGroup(
            panelLineChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLineChartLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelLineChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLineChartLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(panelLineChartLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 468, Short.MAX_VALUE))
                    .addGroup(panelLineChartLayout.createSequentialGroup()
                        .addGroup(panelLineChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLineChartLayout.createSequentialGroup()
                                .addGroup(panelLineChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLineChartLayout.createSequentialGroup()
                                        .addGroup(panelLineChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Jan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(panelLineChartLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel1)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(panelLineChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Feb, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(panelLineChartLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel7)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(panelLineChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Mar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(panelLineChartLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel8)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelLineChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Apr, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelLineChartLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel9)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelLineChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Mei, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelLineChartLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel10)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelLineChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Jun, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                    .addGroup(panelLineChartLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel11))
                                    .addComponent(JunLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelLineChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Jul, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                    .addGroup(panelLineChartLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel12))
                                    .addComponent(JulLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelLineChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Aug, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelLineChartLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel13))))
                            .addGroup(panelLineChartLayout.createSequentialGroup()
                                .addComponent(JanLab, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FebLab, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(MarLab, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AprLab, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MayLab, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(104, 104, 104)
                                .addComponent(AugLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelLineChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLineChartLayout.createSequentialGroup()
                                .addGroup(panelLineChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Sep, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelLineChartLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel14)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelLineChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Okt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelLineChartLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel15))))
                            .addGroup(panelLineChartLayout.createSequentialGroup()
                                .addComponent(SepLab, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(OktLab, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelLineChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLineChartLayout.createSequentialGroup()
                                .addGroup(panelLineChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Nov, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelLineChartLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel16)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelLineChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelLineChartLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel17)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(panelLineChartLayout.createSequentialGroup()
                                        .addComponent(Des, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 23, Short.MAX_VALUE))))
                            .addGroup(panelLineChartLayout.createSequentialGroup()
                                .addComponent(NovLab, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DesLab, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        panelLineChartLayout.setVerticalGroup(
            panelLineChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLineChartLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(panelLineChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JanLab, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                    .addComponent(JunLab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FebLab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MarLab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AprLab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MayLab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JulLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OktLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DesLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AugLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SepLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NovLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLineChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLineChartLayout.createSequentialGroup()
                        .addComponent(Nov, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16))
                    .addGroup(panelLineChartLayout.createSequentialGroup()
                        .addComponent(Des, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLineChartLayout.createSequentialGroup()
                        .addComponent(Okt, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15))
                    .addGroup(panelLineChartLayout.createSequentialGroup()
                        .addComponent(Sep, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14))
                    .addGroup(panelLineChartLayout.createSequentialGroup()
                        .addComponent(Aug, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13))
                    .addGroup(panelLineChartLayout.createSequentialGroup()
                        .addComponent(Jul, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12))
                    .addGroup(panelLineChartLayout.createSequentialGroup()
                        .addComponent(Jun, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addGroup(panelLineChartLayout.createSequentialGroup()
                        .addComponent(Mei, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addGroup(panelLineChartLayout.createSequentialGroup()
                        .addComponent(Apr, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))
                    .addGroup(panelLineChartLayout.createSequentialGroup()
                        .addComponent(Mar, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addGroup(panelLineChartLayout.createSequentialGroup()
                        .addComponent(Feb, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addGroup(panelLineChartLayout.createSequentialGroup()
                        .addComponent(Jan, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addGap(58, 58, 58)
                .addGroup(panelLineChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(panelLineChart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(panelLineChart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 820, 510));

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));
        jPanel2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DASHBOARD");

        panelImport.setBackground(new java.awt.Color(245, 245, 245));
        panelImport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelImportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelImportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelImportMouseExited(evt);
            }
        });
        panelImport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        importData.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        importData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        importData.setText("Upload Data");
        importData.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelImport.add(importData, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 7, -1, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/import (2).png"))); // NOI18N
        panelImport.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        panelData.setBackground(new java.awt.Color(124, 209, 184));
        panelData.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        importData1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        importData1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        importData1.setText("Analysis Data");
        importData1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelData.add(importData1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 7, -1, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/analysis (1).png"))); // NOI18N
        panelData.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        panelQuit.setBackground(new java.awt.Color(245, 245, 245));
        panelQuit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelQuitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelQuitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelQuitMouseExited(evt);
            }
        });
        panelQuit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        importData2.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        importData2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        importData2.setText("Quit");
        importData2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelQuit.add(importData2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 7, -1, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/exit.png"))); // NOI18N
        panelQuit.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(57, 57, 57))
            .addComponent(panelQuit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelImport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addGap(90, 90, 90)
                .addComponent(panelImport, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelData, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                .addComponent(panelQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelQuitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelQuitMouseEntered
        // TODO add your handling code here:
        panelQuit.setBackground(new Color(250, 187, 81));
    }//GEN-LAST:event_panelQuitMouseEntered

    private void panelQuitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelQuitMouseExited
        // TODO add your handling code here:
        panelQuit.setBackground(new Color(245, 245, 245));
    }//GEN-LAST:event_panelQuitMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cl.updateBar(this);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void panelImportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelImportMouseEntered
        // TODO add your handling code here:
        panelImport.setBackground(new Color(250, 187, 81));
    }//GEN-LAST:event_panelImportMouseEntered

    private void panelImportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelImportMouseExited
        // TODO add your handling code here:
        panelImport.setBackground(new Color(245, 245, 245));
    }//GEN-LAST:event_panelImportMouseExited

    private void panelImportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelImportMouseClicked
        // TODO add your handling code here:
        this.dispose(); 
        ViewUpload vp = new ViewUpload();
        vp.setVisible(true);
        vp.pack();
        vp.setLocationRelativeTo(null);
        vp.setDefaultCloseOperation(vp.EXIT_ON_CLOSE);
    }//GEN-LAST:event_panelImportMouseClicked

    private void panelQuitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelQuitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_panelQuitMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        cl.insertBar(this);
    }//GEN-LAST:event_jButton2ActionPerformed

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ViewAnalysis().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JProgressBar Apr;
    public static javax.swing.JLabel AprLab;
    public static javax.swing.JProgressBar Aug;
    public static javax.swing.JLabel AugLab;
    public static javax.swing.JProgressBar Des;
    public static javax.swing.JLabel DesLab;
    public static javax.swing.JProgressBar Feb;
    public static javax.swing.JLabel FebLab;
    public static javax.swing.JProgressBar Jan;
    public static javax.swing.JLabel JanLab;
    public static javax.swing.JProgressBar Jul;
    public static javax.swing.JLabel JulLab;
    public static javax.swing.JProgressBar Jun;
    public static javax.swing.JLabel JunLab;
    public static javax.swing.JProgressBar Mar;
    public static javax.swing.JLabel MarLab;
    public static javax.swing.JLabel MayLab;
    public static javax.swing.JProgressBar Mei;
    public static javax.swing.JProgressBar Nov;
    public static javax.swing.JLabel NovLab;
    public static javax.swing.JProgressBar Okt;
    public static javax.swing.JLabel OktLab;
    public static javax.swing.JProgressBar Sep;
    public static javax.swing.JLabel SepLab;
    private javax.swing.JLabel importData;
    private javax.swing.JLabel importData1;
    private javax.swing.JLabel importData2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelData;
    private javax.swing.JPanel panelImport;
    private javax.swing.JPanel panelLineChart;
    private javax.swing.JPanel panelQuit;
    // End of variables declaration//GEN-END:variables
}
